# Generated by Django 4.1.7 on 2023-03-30 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='patient',
        ),
    ]
