# Generated by Django 4.1.7 on 2023-03-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0005_alter_partner_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='credit_card_month',
            field=models.CharField(max_length=20),
        ),
    ]
