# Generated by Django 4.1.7 on 2023-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0006_alter_partner_credit_card_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='credit_card',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='partner',
            name='credit_card_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='partner',
            name='credit_card_year',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
