# Generated by Django 4.1.7 on 2023-03-30 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deposit', '0007_alter_partner_credit_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='credit_card',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='credit_card_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='credit_card_year',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
