# Generated by Django 4.1.7 on 2023-03-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0008_alter_partner_credit_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='credit_card_month',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='credit_card_year',
        ),
        migrations.AddField(
            model_name='partner',
            name='expire_date',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
