# Generated by Django 4.1.7 on 2023-03-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0009_remove_partner_credit_card_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='credit_card_month',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='credit_card_year',
            field=models.CharField(blank=True, default=0, max_length=2, null=True),
        ),
    ]
