# Generated by Django 4.1.7 on 2023-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0010_partner_credit_card_month_partner_credit_card_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='credit_card',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
