# Generated by Django 4.1.7 on 2023-04-04 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_alter_user_phone_alter_user_role'),
        ('patient', '0005_remove_patientcomehistory_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params0To20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(max_length=6)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Visus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od', models.BooleanField(default=False)),
                ('eye', models.IntegerField(blank=True, choices=[(0, 'OD'), (1, 'OS')], default=0, null=True, verbose_name="Qaysi ko'z?")),
                ('sph', models.FloatField(default=0)),
                ('cyl', models.FloatField(default=0)),
                ('ax', models.IntegerField(default=0)),
                ('bliz', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('bk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bk_set', to='diagnostic.params0to20')),
                ('cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cd_set', to='diagnostic.params0to20')),
                ('ck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ck_set', to='diagnostic.params0to20')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_come_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientcomehistory')),
            ],
        ),
    ]
