# Generated by Django 4.1.7 on 2023-05-31 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visus',
            name='patient_come_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visus_to_patient_come_history', to='patient.patientcomehistory'),
        ),
        migrations.AddField(
            model_name='pupiloftheeye',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='params0to20',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='complaints',
            field=models.ManyToManyField(to='diagnostic.complaint'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='conjunctiva',
            field=models.ManyToManyField(to='diagnostic.conjunctiva'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='cornea',
            field=models.ManyToManyField(to='diagnostic.сornea'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='diagnosis',
            field=models.ManyToManyField(to='diagnostic.diagnosis'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='eyeball',
            field=models.ManyToManyField(to='diagnostic.eyeball'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='eyelids',
            field=models.ManyToManyField(to='diagnostic.eyelids'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='front_camera',
            field=models.ManyToManyField(to='diagnostic.frontcamera'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='lens',
            field=models.ManyToManyField(to='diagnostic.lens'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='ocular_fundus',
            field=models.ManyToManyField(to='diagnostic.ocularfundus'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='patient_come_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ophth_to_patient_come_history', to='patient.patientcomehistory'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='vitreous_body',
            field=models.ManyToManyField(to='diagnostic.vitreousbody'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='zrachok',
            field=models.ManyToManyField(to='diagnostic.pupiloftheeye'),
        ),
        migrations.AddField(
            model_name='ocularfundus',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='lens',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='frontcamera',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='eyelids',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='eyeball',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='conjunctiva',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
        ),
    ]
