# Generated by Django 4.1.7 on 2023-04-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0002_alter_visus_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visus',
            name='od',
        ),
    ]
