# Generated by Django 4.1.7 on 2023-04-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patientcomehistory_card_id_cardtouser'),
        ('diagnostic', '0003_remove_visus_od'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visus',
            name='patient_come_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visus_to_patient_come_history', to='patient.patientcomehistory'),
        ),
    ]
