# Generated by Django 4.1.7 on 2023-04-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0005_complaint_conjunctiva_diagnosis_eyeball_eyelids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocularfundus',
            name='hour_indicator',
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='eye',
            field=models.IntegerField(blank=True, choices=[(0, 'OD'), (1, 'OS')], default=0, null=True, verbose_name="Qaysi ko'z?"),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='hour_indicator',
            field=models.IntegerField(default=0),
        ),
    ]
