# Generated by Django 4.1.7 on 2023-04-14 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patientcomehistory_card_id_cardtouser'),
        ('diagnostic', '0006_remove_ocularfundus_hour_indicator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ophthalmologystatus',
            old_name='patient',
            new_name='doctor',
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='patient_come_history',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ophth_to_patient_come_history', to='patient.patientcomehistory'),
            preserve_default=False,
        ),
    ]
