# Generated by Django 4.1.7 on 2023-04-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0007_rename_patient_ophthalmologystatus_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='conjunctiva',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='cornea',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='eyeball',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='eyelids',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='front_camera',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='lens',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='ocular_fundus',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='vitreous_body',
        ),
        migrations.RemoveField(
            model_name='ophthalmologystatus',
            name='zrachok',
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='complaints',
            field=models.ManyToManyField(to='diagnostic.complaint'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='conjunctiva',
            field=models.ManyToManyField(to='diagnostic.conjunctiva'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='cornea',
            field=models.ManyToManyField(to='diagnostic.сornea'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='diagnosis',
            field=models.ManyToManyField(to='diagnostic.diagnosis'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='eyeball',
            field=models.ManyToManyField(to='diagnostic.eyeball'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='eyelids',
            field=models.ManyToManyField(to='diagnostic.eyelids'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='front_camera',
            field=models.ManyToManyField(to='diagnostic.frontcamera'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='lens',
            field=models.ManyToManyField(to='diagnostic.lens'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='ocular_fundus',
            field=models.ManyToManyField(to='diagnostic.ocularfundus'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='vitreous_body',
            field=models.ManyToManyField(to='diagnostic.vitreousbody'),
        ),
        migrations.AddField(
            model_name='ophthalmologystatus',
            name='zrachok',
            field=models.ManyToManyField(to='diagnostic.pupiloftheeye'),
        ),
    ]
