# Generated by Django 4.1.7 on 2023-04-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0008_remove_ophthalmologystatus_complaints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ophthalmologystatus',
            name='hour_indicator',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
