# Generated by Django 4.1.7 on 2023-04-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0009_alter_ophthalmologystatus_hour_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ophthalmologystatus',
            name='anamnesis',
            field=models.CharField(max_length=255),
        ),
    ]
