# Generated by Django 4.1.7 on 2023-05-31 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sph_od', models.CharField(blank=True, max_length=20, null=True)),
                ('cyl_od', models.CharField(blank=True, max_length=20, null=True)),
                ('ax_od', models.CharField(blank=True, max_length=20, null=True)),
                ('bliz_od', models.CharField(blank=True, max_length=20, null=True)),
                ('sph_os', models.CharField(blank=True, max_length=20, null=True)),
                ('cyl_os', models.CharField(blank=True, max_length=20, null=True)),
                ('ax_os', models.CharField(blank=True, max_length=20, null=True)),
                ('bliz_os', models.CharField(blank=True, max_length=20, null=True)),
                ('dp', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
