# Generated by Django 4.1.7 on 2023-03-29 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payinstalmentcombine',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.installment'),
        ),
        migrations.AddField(
            model_name='payinstalmentcombine',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.service'),
        ),
        migrations.AddField(
            model_name='payinstalmentcombine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payinstallmentperiod',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.installment'),
        ),
        migrations.AddField(
            model_name='payinstallmentperiod',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_installment_period_to_service', to='service.service'),
        ),
        migrations.AddField(
            model_name='payinstallmentperiod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='debts',
            name='pay_installment_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.payinstallmentperiod'),
        ),
    ]
