# Generated by Django 4.1.7 on 2023-04-08 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_phone_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0003_serviceprice_remove_service_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprice',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.clinic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_service_price', to='service.serviceprice'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
