# Generated by Django 4.1.7 on 2023-05-31 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_operations', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=6, null=True)),
                ('between_time', models.CharField(blank=True, max_length=6, null=True)),
                ('lifetime', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expensive_time', models.CharField(choices=[(3, '3'), (6, '6'), (5, '5'), (2, '2'), (7, '7'), (1, '1'), (8, '8'), (4, '4')], default=1, max_length=3)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drug.drugs')),
            ],
        ),
    ]
