# Generated by Django 4.1.7 on 2023-04-28 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_phone_alter_user_role'),
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.clinic'),
        ),
    ]
