# Generated by Django 4.1.7 on 2023-03-30 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit', '0003_remove_partner_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientComeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('come_date', models.DateTimeField(auto_now_add=True)),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deposit.partner')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NextCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_come', models.DateTimeField(auto_now_add=True)),
                ('patient_come_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patientcomehistory')),
            ],
        ),
    ]
