# Generated by Django 4.1.7 on 2023-04-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_alter_partner_credit_card'),
        ('patient', '0002_alter_patientcomehistory_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcomehistory',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deposit.partner'),
        ),
    ]
