# Generated by Django 4.1.7 on 2023-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patientcomehistory_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcomehistory',
            name='slug',
            field=models.SlugField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
