# Generated by Django 4.1.7 on 2023-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientcomehistory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomehistory',
            name='slug',
        ),
        migrations.AddField(
            model_name='patientcomehistory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
