# Generated by Django 4.1.7 on 2023-04-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0005_remove_patientcomehistory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcomehistory',
            name='card_id',
        ),
        migrations.CreateModel(
            name='CardToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_to_user_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
