# Generated by Django 4.1.7 on 2023-04-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_patientcomehistory_card_id_cardtouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id_qr', models.CharField(blank=True, max_length=10, null=True)),
                ('fio', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
