# Generated by Django 4.1.7 on 2023-04-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0011_alter_partner_credit_card'),
        ('patient', '0007_qrcoderegister'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(blank=True, max_length=200, null=True)),
                ('qr_phone', models.CharField(max_length=15, unique=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deposit.partner')),
            ],
        ),
    ]
