# Generated by Django 4.1.7 on 2023-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_qrcodepartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('code', models.CharField(max_length=6)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
