# Generated by Django 4.1.7 on 2023-04-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_phonecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcoderegister',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='qrcoderegister',
            name='qr_phone',
            field=models.CharField(max_length=15),
        ),
    ]
