# Generated by Django 4.1.7 on 2023-04-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_qrcoderegister_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoderegister',
            name='qr_phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
