# Generated by Django 4.1.7 on 2023-04-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_alter_qrcoderegister_qr_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoderegister',
            name='qr_phone',
            field=models.CharField(max_length=15),
        ),
    ]
