# Generated by Django 4.1.7 on 2023-04-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_qrcoderegister_qr_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodepartner',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
