# Generated by Django 4.1.7 on 2023-04-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_qrcoderegister'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
