# Generated by Django 4.1.7 on 2023-04-08 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_serviceprice_remove_service_cost_and_more'),
        ('lead', '0003_lead_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.AddField(
            model_name='lead',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='service.service'),
            preserve_default=False,
        ),
    ]
