# Generated by Django 4.1.7 on 2023-04-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_remove_lead_user_lead_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_price',
            field=models.IntegerField(default=0),
        ),
    ]
